name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      # Install project
      - name: Install project
        run: npm install

      # Build project
      - name: Build project
        run: npm start & >  build.log 2>&1

      # Push to Github Pages
      - name: Github Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # Build directory to deploy
          target_branch: main
          build_dir: /
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}